[package]
name = "usb_dongle"
version = "0.1.0"
edition = "2021"

[dependencies]
tropic-rs = { path = "../../tropic-rs", features = ["display", "serde"] }
tropic-cert-decoder = { path = "../../tropic-cert-decoder", features = [
    "nom-decoder",
    "serde",
] }

serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1.0"
pem = "3.0"
pkcs8 = { version = "0.10", features = ["pem"] }
rand = "0.9"

clap = { version = "4.5", features = ["derive"] }
thiserror = "2"
anyhow = "1"
directories = "6.0.0"

serial2 = "0.2.33"

[[bin]]
name = "tropic-usb-dongle"
path = "src/bin/tropic_usb_dongle.rs"
