[package]
name = "tropic-cert-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
der = { version = "0.7", default-features = false, features = [
    "derive",
    "oid",
], optional = true }
der_derive = { version = "0.7", default-features = false, optional = true }
spki = { version = "0.7", default-features = false, optional = true }

nom = { version = "8", default-features = false, optional = true }

defmt = { version = "1", default-features = false, optional = true }

serde = { version = "1.0", features = ["derive"], optional = true }
base64ct = { version = "1.8", features = [], optional = true }
hex = { package = "const-hex", version = "1.17", optional = true }

x25519-dalek = { version = "2.0", default-features = false, features = [
    "static_secrets",
] }

[features]
default = ["der-decoder", "nom-decoder"]
display = []
defmt = ["dep:defmt"]
der-decoder = ["dep:der", "dep:der_derive", "dep:spki"]
nom-decoder = ["dep:nom"]
serde = ["dep:serde", "dep:base64ct", "dep:hex"]

[dev-dependencies]
serde_json = "1"
